1.`numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None)`

* start:序列开始
* stop：序列的结束，endpoint为False则没有。
* restep:如果True，返回(samples,step)，step是样本减的间隔

In [1]:
from pylab import * 

In [2]:
linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [3]:
linspace(2.0,3.0,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [4]:
linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

2. `random(size=None)`返回半开区间`[0.0,1.0)`

In [6]:
random_sample()

0.06496032290123943

In [15]:
random_sample()

0.3453743113266512

In [7]:
random()

0.4585094543088215

In [10]:
randint(5,size=10)  # 在产生10个整数，∈[0,5)

array([3, 2, 4, 3, 3, 1, 0, 3, 4, 1])

In [11]:
randint(5,size=(2,4)) #产生２ｘ４矩阵，范围为∈[0,5)

array([[2, 4, 3, 1],
       [1, 4, 1, 0]])

In [13]:
rand(3,2)  #产生给定形状随机数

array([[0.12211484, 0.47858594],
       [0.52394549, 0.44536935],
       [0.82743507, 0.97787074]])